### ISSUE TITLE
No Weapon after the second Random Box usage

### ISSUE THREAD

**Issue by DammitStella** [Zet0rz/nzombies#193]
After you use the random weapon box an second time, you won't get the weapon it says.
Instead you'll equip the M67 Grenade and you can't swap your weapons.
After pressing the melee, you get atleast back to your old weapon.

setup: S.T.A.L.K.E.R Weapons, ttt_kosovos with modified save (can upload the files, if needed) and Pointshop 1.
Workshop collection: http://steamcommunity.com/sharedfiles/filedetails/?id=253617215

**Comment by func-octo** [comment]
Type `lua_run PrintTable(hook.GetTable())` in the console and comment back with what the console says.

**Comment by DammitStella** [comment]
https://gist.github.com/Tomelyr/79f72259815ceca1f10e8dda7c4df0d8

incase live action editing of the server would help, feel free to add me on steam.

**Comment by func-octo** [comment]
Are you using ULX Admin? If so, disable it and try again. Cheers :)

**Comment by DammitStella** [comment]
I have disabled: ULX and PS (basicly clean) and the issue persisted.
if needed, i can upload an showcase video of it

**Comment by func-octo** [comment]
That may not be necessary. Let's see if zetorz knows what it is.

**Comment by DammitStella** [comment]
I've gone ahead and recorded it
https://www.youtube.com/watch?v=q3scKXL4LSw&feature=youtu.be
(Headphone warning, somehow yt screwed up and the volume is kinda loud, so please just mute it)
0:14 - glitching inside the first spawn on kosovos, 
1:30 first Random box
2:30 second box
3:20 third box

Edit://
I just realised, that the same behavior can happen with Wall bought weapons. First buy okay, second buy is screwing everything up. i think the culprit is weapons/sv_weps.lua. will look more closely into it, as soon i get the cheats to work properly.

**Comment by Zet0rz** [comment]
The infamous M67 Bug. Fully aware of it and have no clue what it's caused by. I'm hoping it will fix itself when I remake the grenade, but for now use the convar `nz_failsafe_preventgrenades` which cause you to not get grenades at all, eliminating the issue at the cost of the grenades. It's only a temporary solution though. 

The bug seems to happen with certain weapon packs more often than others (never happened to me with the ones we use officially). It has nothing to do with admin rights or hooks.

**Comment by jaxjaxk** [comment]
i would look at the swap weapons code. that has a lot of bugs in it and is kind of complex.

**Comment by jaxjaxk** [comment]
one way i fixed this is for the grenades, monkey bombs and morphine placed this in the primary attack function.

"timer.Simple(5,function()
if self:IsValid() then 
self.WepOwner:SetActiveWeapon(nil)
self.WepOwner:EquipPreviousWeapon()

end"

this simply reverts the weapon back after 5 seconds if you still have it. it's a good temp fix.

**Comment by jaxjaxk** [comment]
also this might relate to the problem but this is run frequently on my server

print(ply:Nick().."'s UsingSpecialWeapon status was true but he isn't equipped with a special weapon and isn't trying to. Resetting ...")

so they might just have a special weapon issue

**Comment by DammitStella** [comment]
While nz_failsafe_preventgrenades indeed didn't gave me the Grenade, it still doesn't function properly.
I'm still not able to purchase an second weapon, The random box gives me up to 3 weapons, but after that, it doesn't add one up or removes one.

The Wallbuy in particular isn't stripping the old one correctly. Basicly it's stripping the new weapon.
But it's already 3 am here, so i'll look further into it when i got some sleep. 

edit:// Couldnt sleep yet.
ive changed line 414 in sv_weps to

```
                if exists then
                    print(ply:GetActiveWeapon():GetClass())
                    ply:StripWeapon( ply:GetActiveWeapon():GetClass() ) 
                end
```

And the console output was "stalker_eliminator" while my previous weapon was "stalker_svu", when i've tried to buy stalker_eliminator

**Comment by Zet0rz** [comment]
That's interesting. That might actually be it. I will look into this ASAP, but I have some exam projects that take priority atm. Definitely some time before the weekend though.

**Comment by func-octo** [comment]
@Zet0rz I exempt my exams xD (I really should've tested out of IT Fundamentals though.) Good luck to you!

**Comment by DammitStella** [comment]
So. I have an idea to fix this issue once and hopefully for all.
But to test this idea, i'll need some help from someone who knows the design documents well.

My Idea so far: 
Modify GetPriorityWeaponSlot(), so it returns the wep class with it inside the loop. But that way, it'll remove weapon 3, when you have mulekick. I don't know, which weapons to remove properly.
I could rewrite it, that it'll remove the second weapon, but on the other hand, is that the way it should go?

edit://
Got some testcode running. While indeed, the wallbuy now functions properly, it still is screwing over me a bit. The second SWEP is there correctly, but as soon i switch back to annother, i cant swap back to it. Forgott to print some results, brb

edit2://
Found the issue. The new weapon got the ID of 4 instead of 3, defacto adding one instead of removing. That's why i can't swap back. So the weapon needs to be removed even earlier. Better would be in another hook, which runs before he gets the new one. And it gets worse after that.
Basicly im now removing 3 the whole time, but adding on top of each other. So after a few buys, the table is now filled up to 8, but still cant use any of them. 
So other hook or recounting of the weapon table. nice...

Edit3://
Can someone explain me how GetNWInt("SwitchSlot", 1) is exactly used and for what reason? It doesn't matter what weapon i have, how much i have or which perks i have. it always print out 2 for me inside GetPrioritySlot

**Comment by Zet0rz** [comment]
I'll look into it when I can. It might actually be smart for the function to return the class of the found weapon in the loop so we can remove it based on that.

**Comment by DammitStella** [comment]
Current WIP Code from my side.
https://gist.github.com/Tomelyr/1f90cf8a294e954b78dabeed68683ff4
But still. Something is wrong.
Especially, after all my tests, the SwitchSlot is the conflicting currently.

> lua_run for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end
> for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end...
> 1
> 0
> 1
> 1
> 1

After this console log (with a lot of lua_runs :))

> lua_run print(player.GetByID(1))
> print(player.GetByID(1))...
> Player [1][[CE] Baus Kingski]
> lua_run print(GetPriorityWeaponSlot(player.GetByID(1)))
> print(GetPriorityWeaponSlot(player.GetByID(1)))...
> 2       true    stalker_spas
> lua_run PrintTable(player.GetByID(1):GetWeapons())
> PrintTable(player.GetByID(1):GetWeapons())...
> 1       =       Weapon [873][stalker_baretta_single]
> 2       =       Weapon [874][nz_quickknife_crowbar]
> 3       =       Weapon [226][stalker_spas]
> PrintTable(player.GetByID(1):GetWeapons())...
> 1       =       Weapon [873][stalker_baretta_single]
> 2       =       Weapon [874][nz_quickknife_crowbar]
> 4       =       Weapon [123][stalker_baretta_dual]
> Killed Enemy: 1/5
> lua_run PrintTable(player.GetByID(1):GetWeapons())
> PrintTable(player.GetByID(1):GetWeapons())...
> 1       =       Weapon [873][stalker_baretta_single]
> 2       =       Weapon [874][nz_quickknife_crowbar]
> 3       =       Weapon [124][stalker_dragunov]
> 4       =       Weapon [123][stalker_baretta_dual]
> ActiveSWEP: stalker_ak74_u
> rmSwep: stalker_dragunov
> lua_run PrintTable(player.GetByID(1):GetWeapons())
> PrintTable(player.GetByID(1):GetWeapons())...
> 1       =       Weapon [873][stalker_baretta_single]
> 2       =       Weapon [874][nz_quickknife_crowbar]
> 4       =       Weapon [123][stalker_baretta_dual]
> 5       =       Weapon [127][stalker_ak74_u]
> lua_run print(GetPriorityWeaponSlot(player.GetByID(1)))
> print(GetPriorityWeaponSlot(player.GetByID(1)))...
> 2
> lua_run print(GetPriorityWeaponSlot(player.GetByID(1)))
> print(GetPriorityWeaponSlot(player.GetByID(1)))...
> 2       true    stalker_g36
> lua_run print(GetPriorityWeaponSlot(player.GetByID(1)))
> print(GetPriorityWeaponSlot(player.GetByID(1)))...
> 2       true    stalker_g36
> lua_run PrintTable(player.GetByID(1):GetWeapons())
> PrintTable(player.GetByID(1):GetWeapons())...
> 1       =       Weapon [873][stalker_baretta_single]
> 2       =       Weapon [874][nz_quickknife_crowbar]
> 3       =       Weapon [124][stalker_g36]
> 4       =       Weapon [123][stalker_baretta_dual]
> 5       =       Weapon [127][stalker_ak74_u]
> lua_run print(GetPriorityWeaponSlot(player.GetByID(1)))ActiveSWEP: stalker_abaton
> rmSwep: stalker_g36
> 
> print(GetPriorityWeaponSlot(player.GetByID(1)))...
> 2
> lua_run PrintTable(player.GetByID(1):GetWeapons())
> PrintTable(player.GetByID(1):GetWeapons())...
> 1       =       Weapon [873][stalker_baretta_single]
> 2       =       Weapon [874][nz_quickknife_crowbar]
> 4       =       Weapon [123][stalker_baretta_dual]
> 5       =       Weapon [127][stalker_ak74_u]
> 6       =       Weapon [132][stalker_abaton]

**Comment by func-octo** [comment]
The confusion...

**Comment by DammitStella** [comment]
But i isolated the problem even further. 

> lua_run for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end
> for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end...
> 1
> 0
> 2
> ActiveSWEP: stalker_baretta_dual
> rmSwep: stalker_dragunov
> lua_run for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end
> for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end...
> 1
> 0
> 1

To speak simple, as soon the cap is reached, the GetNWInt is plain out not working, because it grabs the ~~wrong data~~. the non set NWint of the new weapon instead.

**Comment by DammitStella** [comment]
Issue solved, pull request will come in a few minutes after this.

**Comment by Zet0rz** [comment]
I will have to remake the system anyway, but I'll gladly look into your solution and likely use it in the rewrite when I get that far. Thanks for your help :)

**Comment by DammitStella** [comment]
it's pretty simple. Basicly im altering the plymeta when a new weapon is givin out (wallbought, misterybox) and using this data with an failsafe instead. PR will take a bit, since the cloning of this repo take ages.
